package week2.thursday.task3;

public enum Country {
    CHINA, JAPAN, KOREA,  // ASIA
    EGYPT, NIGERIA, CAMEROON, // AFRICA
    USA, MEXICO, CANADA, // NORTH_AMERICA
    BRAZIL, COLOMBIA, ARGENTINA, // SOUTH_AMERICA
    UKRAINE, GERMANY, POLAND, // EUROPE
    AUSTRALIA //AUSTRALIA
}
